Repository PennLINC/xcp_d, pull requests merged in 2022-10, with the labels that each got.

#542 [TST] Check for existence of outputs in tests
  .circleci/cifti_with_freesurfer_outputs.txt
  .circleci/config.yml
  .circleci/nifti_with_freesurfer_outputs.txt
  .circleci/nifti_without_freesurfer_outputs.txt
Labels: testing

#550 [TST] Restructure local patch handling in testing setup
  .circleci/get_data.sh
  .gitignore
  docs/dev_guide.rst
Labels: documentation, testing

#540 [FIX] Fix "manadatory" typo in interfaces
  xcp_d/interfaces/connectivity.py
  xcp_d/interfaces/filtering.py
  xcp_d/interfaces/prepostcleaning.py
  xcp_d/interfaces/qc_plot.py
  xcp_d/interfaces/regression.py
  xcp_d/interfaces/resting_state.py
  xcp_d/interfaces/surfplotting.py
Labels: bug

#535 [REF] Remove unused init_post_process_wf
  xcp_d/utils/bids.py
  xcp_d/workflow/postprocessing.py
Labels: refactor

#549 [ENH] Add func-only option
  xcp_d/cli/run.py
  xcp_d/workflow/base.py
Labels: enhancement

#546 [REF] Use MapNodes to simplify functional connectivity workflows
  xcp_d/interfaces/connectivity.py
  xcp_d/utils/atlas.py
  xcp_d/utils/doc.py
  xcp_d/utils/utils.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
  xcp_d/workflow/connectivity.py
  xcp_d/workflow/outputs.py
Labels: refactor

#552 Add release notes template
  .github/release.yml
  docs/dev_guide.rst
Labels: maintenance

#541 [FIX] Ensure TSV files are tab-delimited
  docs/usage.rst
  xcp_d/interfaces/connectivity.py
  xcp_d/interfaces/prepostcleaning.py
  xcp_d/interfaces/workbench.py
  xcp_d/utils/concantenation.py
  xcp_d/utils/fcon.py
Labels: bug, breaking-change

#560 [FIX] Change "hpc" in CLI to "hcp"
  xcp_d/cli/run.py
Labels: bug

#537 [ENH/FIX] Update required pybids ver
  setup.cfg
Labels: bug, maintenance

#561 Create dataset description file
  .circleci/cifti_with_freesurfer_outputs.txt
  .circleci/nifti_with_freesurfer_outputs.txt
  .circleci/nifti_without_freesurfer_outputs.txt
  setup.cfg
  xcp_d/cli/run.py
  xcp_d/utils/bids.py
  xcp_d/workflow/base.py
Labels: enhancement

#496 Fix resampling of fsnative structural surfaces to fsLR
  setup.cfg
  xcp_d/workflow/anatomical.py
Labels: bug

#553 Rename derivatives to be more BIDS-compliant
  .circleci/cifti_with_freesurfer_outputs.txt
  .circleci/nifti_with_freesurfer_outputs.txt
  .circleci/nifti_without_freesurfer_outputs.txt
  docs/output.rst
  xcp_d/data/nipreps.json
  xcp_d/workflow/anatomical.py
  xcp_d/workflow/outputs.py
Labels: enhancement, breaking-change

#567 Distinguish preprocessed dataset formats
  xcp_d/cli/run.py
  xcp_d/data/boilerplate.bib
  xcp_d/utils/bids.py
  xcp_d/utils/doc.py
  xcp_d/workflow/base.py
Labels: enhancement

#572 Add warning to documentation about M1 chip
  docs/usage.rst
Labels: documentation

#530 Improve confound plot readability and fix moving registration plot
  xcp_d/data/reports.yml
  xcp_d/interfaces/constants.py
  xcp_d/utils/plot.py
  xcp_d/utils/qcmetrics.py
  xcp_d/workflow/bold.py
Labels: refactor

#575 Fix documentation and validation of motion filtering parameters
  .circleci/CiftiWithFreeSurferTest.sh
  .circleci/NiftiWithoutFreeSurferTest.sh
  .circleci/tests/data/band_passed_bold_data.txt
  .circleci/tests/data/low_passed_MR_data.txt
  .circleci/tests/data/notched_MR_data.txt
  .circleci/tests/data/raw_data.txt
  .circleci/tests/test_FD.py
  .circleci/tests/test_filtering.py
  docs/generalworkflow.rst
  xcp_d/cli/run.py
  xcp_d/data/boilerplate.bib
  xcp_d/interfaces/prepostcleaning.py
  xcp_d/interfaces/qc_plot.py
  xcp_d/utils/confounds.py
  xcp_d/utils/doc.py
  xcp_d/workflow/base.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
Labels: bug, documentation

#562 Replace `--func-only` with `--warp-surfaces-native2std`
  .circleci/CiftiWithFreeSurferTest.sh
  .circleci/NiftiWithFreeSurferTest.sh
  .circleci/NiftiWithoutFreeSurferTest.sh
  .circleci/cifti_with_freesurfer_outputs.txt
  .circleci/nifti_with_freesurfer_outputs.txt
  .circleci/nifti_without_freesurfer_outputs.txt
  docs/output.rst
  docs/workflows.rst
  xcp_d/cli/run.py
  xcp_d/interfaces/qc_plot.py
  xcp_d/interfaces/report_core.py
  xcp_d/utils/bids.py
  xcp_d/utils/doc.py
  xcp_d/utils/utils.py
  xcp_d/workflow/anatomical.py
  xcp_d/workflow/base.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
  xcp_d/workflow/connectivity.py
  xcp_d/workflow/execsummary.py
Labels: enhancement, breaking-change

#564 Fix the local pytest script and documentation
  .circleci/RunPyTests.sh
  docs/dev_guide.rst
Labels: documentation, testing

#529 [TEST] Add tests for outstanding modules
  .circleci/tests/test_ALFF.py
  .circleci/tests/test_conn.py
  .circleci/tests/test_despike.py
  .circleci/tests/test_reho.py
  xcp_d/interfaces/surfplotting.py
Labels: testing

#581 Show framewise displacement before filtering in QCPlot
  xcp_d/interfaces/qc_plot.py
  xcp_d/utils/confounds.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
Labels: bug

#584 [FIX] Fcon workflow tests are incompatible with changes from main
  .circleci/tests/test_conn.py
Labels: testing

#586 Output temporal mask
  .circleci/cifti_with_freesurfer_outputs.txt
  .circleci/nifti_with_freesurfer_outputs.txt
  .circleci/nifti_without_freesurfer_outputs.txt
  docs/output.rst
  xcp_d/data/nipreps.json
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
  xcp_d/workflow/outputs.py
Labels: enhancement

#587 Add headers to motion.tsv and outliers.tsv files
  .circleci/tests/test_interpolation.py
  docs/output.rst
  xcp_d/interfaces/prepostcleaning.py
  xcp_d/interfaces/qc_plot.py
  xcp_d/utils/plot.py
Labels: enhancement, breaking-change

#592 Output all filtered motion parameters
  .circleci/cifti_with_freesurfer_outputs.txt
  .circleci/nifti_with_freesurfer_outputs.txt
  .circleci/nifti_without_freesurfer_outputs.txt
  docs/output.rst
  xcp_d/interfaces/prepostcleaning.py
  xcp_d/interfaces/qc_plot.py
  xcp_d/interfaces/surfplotting.py
  xcp_d/utils/plot.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
  xcp_d/workflow/execsummary.py
  xcp_d/workflow/outputs.py
Labels: enhancement

#588 Deprecate `--bandpass_filter` in favor of `--disable-bandpass-filter`
  docs/generalworkflow.rst
  xcp_d/cli/run.py
Labels: enhancement, deprecation

#593 Fix concatenation code w.r.t. recent output changes
  .circleci/CiftiWithFreeSurferTest.sh
  .circleci/cifti_with_freesurfer_outputs.txt
  xcp_d/utils/concantenation.py
  xcp_d/utils/plot.py
  xcp_d/workflow/cifti.py
Labels: bug

#596 Use user-requested parameters in regression
  .circleci/tests/test_Reg.py
  xcp_d/interfaces/regression.py
  xcp_d/utils/confounds.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
Labels: bug

#599 [FIX] Update load_aroma so the correct file is being read in
  xcp_d/interfaces/regression.py
  xcp_d/utils/confounds.py
Labels: bug

#601 Output ReHo as a CIFTI
  .circleci/cifti_with_freesurfer_outputs.txt
  .circleci/tests/test_reho.py
  docs/output.rst
  xcp_d/interfaces/resting_state.py
  xcp_d/interfaces/workbench.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
  xcp_d/workflow/outputs.py
  xcp_d/workflow/restingstate.py
Labels: enhancement, breaking-change

#600 Use BIDSLayout in concatenation code
  .circleci/cifti_with_freesurfer_outputs.txt
  .circleci/tests/test_conn.py
  xcp_d/cli/run.py
  xcp_d/data/nipreps.json
  xcp_d/interfaces/qc_plot.py
  xcp_d/interfaces/report_core.py
  xcp_d/utils/bids.py
  xcp_d/utils/concantenation.py
  xcp_d/utils/concatenation.py
  xcp_d/utils/utils.py
  xcp_d/workflow/anatomical.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/outputs.py
Labels: enhancement, refactor

#607 Use Nilearn for brainsprite generation
  setup.cfg
  xcp_d/data/transform/brainsprite_template.html
  xcp_d/interfaces/resting_state.py
  xcp_d/utils/bids.py
  xcp_d/utils/execsummary.py
Labels: refactor, maintenance

#609 Remove unused functions
  xcp_d/cli/version.py
  xcp_d/utils/dcan2fmriprep.py
  xcp_d/utils/filemanip.py
  xcp_d/utils/plot.py
  xcp_d/utils/write_save.py
  xcp_d/workflow/base.py
Labels: maintenance, ignore-for-release

#611 Update README.rst
  README.rst
Labels: documentation, ignore-for-release

#608 Remove unused classes
  xcp_d/interfaces/c3.py
  xcp_d/interfaces/resting_state.py
  xcp_d/interfaces/surfplotting.py
  xcp_d/interfaces/workbench.py
  xcp_d/utils/execsummary.py
Labels: maintenance, ignore-for-release

#606 Remove unused dependencies
  .circleci/config.yml
  setup.cfg
Labels: maintenance, ignore-for-release

#603 Select BOLD files in a single space
  xcp_d/utils/bids.py
  xcp_d/utils/concatenation.py
  xcp_d/workflow/base.py
Labels: bug

#617 Update CITATION.cff file for 0.2.0
  CITATION.cff
Labels: maintenance, ignore-for-release

#619 Revert removed code from nibabies PR
  xcp_d/utils/bids.py
Labels: ignore-for-release
