Repository PennLINC/xcp_d, pull requests merged in 2022-11, with the labels that each got.

#624 Reduce executive summary figure size
  xcp_d/utils/concatenation.py
  xcp_d/utils/plot.py
Labels: bug, testing, ignore-for-release

#628 Only generate ALFF derivatives if bandpass filtering is enabled
  .circleci/NiftiWithoutFreeSurferTest.sh
  .circleci/nifti_without_freesurfer_outputs.txt
  docs/output.rst
  xcp_d/cli/run.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
  xcp_d/workflow/outputs.py
Labels: bug

#629 Cache the downloaded test data
  .circleci/config.yml
  .circleci/get_data.sh
Labels: testing

#635 Remove brainsprite and tempita from requirements
  setup.cfg
Labels: ignore-for-release

#621 Use BIDSLayout instead of globbing functions to collect necessary files
  .circleci/NiftiWithFreeSurferTest.sh
  .circleci/get_data.sh
  .circleci/tests/test_ALFF.py
  .circleci/tests/test_conn.py
  .circleci/tests/test_despike.py
  xcp_d/cli/run.py
  xcp_d/utils/bids.py
  xcp_d/utils/concatenation.py
  xcp_d/utils/filemanip.py
  xcp_d/utils/plot.py
  xcp_d/utils/utils.py
  xcp_d/workflow/base.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
Labels: refactor

#633 Do not merge in concatenated files when re-running concatenation workflow
  .circleci/CiftiWithFreeSurferTest.sh
  xcp_d/utils/concatenation.py
Labels: bug

#634 Write confounds out to derivatives
  .circleci/cifti_with_freesurfer_outputs.txt
  .circleci/nibabies_outputs.txt
  .circleci/nifti_with_freesurfer_outputs.txt
  .circleci/nifti_without_freesurfer_outputs.txt
  docs/output.rst
  xcp_d/data/nipreps.json
  xcp_d/interfaces/prepostcleaning.py
  xcp_d/utils/utils.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
  xcp_d/workflow/outputs.py
Labels: enhancement

#638 Start to standardize interface parameter calls
  xcp_d/interfaces/ants.py
  xcp_d/interfaces/c3.py
  xcp_d/interfaces/filtering.py
  xcp_d/interfaces/prepostcleaning.py
  xcp_d/interfaces/qc_plot.py
  xcp_d/interfaces/regression.py
  xcp_d/interfaces/report.py
  xcp_d/interfaces/resting_state.py
  xcp_d/interfaces/surfplotting.py
  xcp_d/interfaces/workbench.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
Labels: refactor

#641 Add column names to confounds df
  .circleci/tests/test_Reg.py
  setup.cfg
  xcp_d/interfaces/regression.py
  xcp_d/utils/confounds.py
Labels: enhancement

#654 Map abbreviated entities to full names for templateflow get call
  xcp_d/utils/plot.py
Labels: bug

#655 Ensure `dummyscans` is an integer in PlotSVGData
  .circleci/NiftiWithFreeSurferTest.sh
  xcp_d/interfaces/surfplotting.py
  xcp_d/utils/concatenation.py
  xcp_d/utils/plot.py
  xcp_d/workflow/execsummary.py
Labels: bug

#640 Lint with black without linting workflow connections
  .github/workflows/lint.yml
  pyproject.toml
  xcp_d/__about__.py
  xcp_d/__init__.py
  xcp_d/__main__.py
  xcp_d/cli/combineqc.py
  xcp_d/cli/run.py
  xcp_d/interfaces/bids.py
  xcp_d/interfaces/connectivity.py
  xcp_d/interfaces/constants.py
  xcp_d/interfaces/filtering.py
  xcp_d/interfaces/layout_builder.py
  xcp_d/interfaces/nilearn.py
  xcp_d/interfaces/prepostcleaning.py
  xcp_d/interfaces/regression.py
  xcp_d/interfaces/report.py
  xcp_d/interfaces/report_core.py
  xcp_d/interfaces/resting_state.py
  xcp_d/interfaces/surfplotting.py
  xcp_d/interfaces/workbench.py
  xcp_d/utils/atlas.py
  xcp_d/utils/bids.py
  xcp_d/utils/concatenation.py
  xcp_d/utils/confounds.py
  xcp_d/utils/dcan2fmriprep.py
  xcp_d/utils/doc.py
  xcp_d/utils/execsummary.py
  xcp_d/utils/fcon.py
  xcp_d/utils/filemanip.py
  xcp_d/utils/hcp2fmriprep.py
  xcp_d/utils/modified_data.py
  xcp_d/utils/plot.py
  xcp_d/utils/qcmetrics.py
  xcp_d/utils/sentry.py
  xcp_d/utils/utils.py
  xcp_d/utils/write_save.py
  xcp_d/workflow/anatomical.py
  xcp_d/workflow/base.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
  xcp_d/workflow/connectivity.py
  xcp_d/workflow/execsummary.py
  xcp_d/workflow/outputs.py
  xcp_d/workflow/postprocessing.py
  xcp_d/workflow/restingstate.py
Labels: refactor, maintenance

#650 Add `--dcan-qc` flag
  .circleci/CiftiWithFreeSurferTest.sh
  .circleci/Nibabies.sh
  .circleci/NiftiWithoutFreeSurferTest.sh
  .circleci/nibabies_outputs.txt
  .circleci/nifti_with_freesurfer_outputs.txt
  xcp_d/cli/run.py
  xcp_d/data/reports.yml
  xcp_d/interfaces/report_core.py
  xcp_d/interfaces/surfplotting.py
  xcp_d/utils/concatenation.py
  xcp_d/utils/plot.py
  xcp_d/workflow/base.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
  xcp_d/workflow/execsummary.py
Labels: enhancement, breaking-change

#642 Support custom confounds with headers
  .circleci/tests/test_FD.py
  .circleci/tests/test_confounds.py
  docs/output.rst
  docs/usage.rst
  xcp_d/cli/run.py
  xcp_d/data/nipreps.json
  xcp_d/interfaces/prepostcleaning.py
  xcp_d/utils/confounds.py
  xcp_d/utils/modified_data.py
  xcp_d/utils/plot.py
  xcp_d/utils/utils.py
  xcp_d/workflow/base.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
Labels: enhancement, breaking-change

#657 Run the full CircleCI workflow on releases
  .circleci/config.yml
  CITATION.cff
Labels: maintenance, ignore-for-release

#658 Remove `--nuissance-regressors` and `--bandpass_filter`
  .circleci/Nibabies.sh
  docs/generalworkflow.rst
  xcp_d/cli/run.py
  xcp_d/utils/utils.py
Labels: breaking-change

#660 Remove dummy volumes from custom confounds files
  xcp_d/interfaces/prepostcleaning.py
Labels: bug

#661 Remove dummy volumes from beginning of each run in concatenation workflow
  .circleci/CiftiWithFreeSurferTest.sh
  xcp_d/interfaces/surfplotting.py
  xcp_d/utils/concatenation.py
  xcp_d/utils/modified_data.py
  xcp_d/utils/plot.py
Labels: bug

#616 Add `--dummy-scans` parameter and deprecate `--dummytime`
  .circleci/CiftiWithFreeSurferTest.sh
  .circleci/tests/test_TR.py
  docs/workflows.rst
  xcp_d/cli/combineqc.py
  xcp_d/cli/run.py
  xcp_d/interfaces/bids.py
  xcp_d/interfaces/c3.py
  xcp_d/interfaces/prepostcleaning.py
  xcp_d/interfaces/qc_plot.py
  xcp_d/interfaces/report_core.py
  xcp_d/interfaces/surfplotting.py
  xcp_d/utils/atlas.py
  xcp_d/utils/concatenation.py
  xcp_d/utils/confounds.py
  xcp_d/utils/doc.py
  xcp_d/utils/filemanip.py
  xcp_d/utils/plot.py
  xcp_d/workflow/base.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
  xcp_d/workflow/execsummary.py
  xcp_d/workflow/outputs.py
Labels: enhancement, deprecation

#664 Consolidate confounds at beginning of denoising workflows
  .circleci/tests/test_FD.py
  .circleci/tests/test_Reg.py
  .circleci/tests/test_TR.py
  .circleci/tests/test_confounds.py
  xcp_d/interfaces/prepostcleaning.py
  xcp_d/interfaces/regression.py
  xcp_d/utils/confounds.py
  xcp_d/utils/utils.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
Labels: refactor

#667 Remove unused outputnodes from nifti and cifti workflows
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
Labels: refactor

#670 Retain noise components instead of dropping them in load_aroma
  xcp_d/utils/confounds.py
Labels: bug

#668 Move QC/censoring plots into new workflow
  .circleci/NiftiWithoutFreeSurferTest.sh
  docs/workflows.rst
  xcp_d/interfaces/qc_plot.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
  xcp_d/workflow/outputs.py
  xcp_d/workflow/plotting.py
  xcp_d/workflow/postprocessing.py
  xcp_d/workflow/restingstate.py
Labels: refactor

#649 Testing affines don't change across XCP runs
  .circleci/CiftiWithFreeSurferTest.sh
  .circleci/Nibabies.sh
  .circleci/NiftiWithFreeSurferTest.sh
  .circleci/NiftiWithoutFreeSurferTest.sh
  .circleci/test_affines.py
  .circleci/tests/test_utils.py
Labels: testing

#677 Update README.rst
  README.rst
Labels: documentation, ignore-for-release

#688 Use input_type to determine order of preferred spaces
  docs/workflows.rst
  xcp_d/utils/bids.py
  xcp_d/workflow/base.py
  xcp_d/workflow/cifti.py
  xcp_d/workflow/execsummary.py
  xcp_d/workflow/plotting.py
Labels: bug

#689 Infer volumetric space from transform in executive summary with cifti data
  xcp_d/utils/bids.py
  xcp_d/utils/utils.py
  xcp_d/workflow/execsummary.py
Labels: bug

#686 Add `--bids-filter-file` parameter
  .circleci/tests/test_conn.py
  docs/usage.rst
  xcp_d/cli/run.py
  xcp_d/utils/bids.py
  xcp_d/utils/doc.py
  xcp_d/utils/utils.py
  xcp_d/workflow/anatomical.py
  xcp_d/workflow/base.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
  xcp_d/workflow/connectivity.py
  xcp_d/workflow/execsummary.py
  xcp_d/workflow/plotting.py
Labels: enhancement

#693 Load basic AROMA confounds
  docs/generalworkflow.rst
  xcp_d/utils/confounds.py
Labels: bug

#695 Select best volumetric space even when using `--cifti` flag
  xcp_d/utils/bids.py
Labels: bug

#666 Downcast >32-bit files to 32-bit
  .circleci/tests/test_prepostcleaning.py
  xcp_d/interfaces/prepostcleaning.py
  xcp_d/utils/modified_data.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
Labels: bug
