Repository PennLINC/xcp_d, pull requests merged in 2022-12, with the labels that each got.

#690 Use appropriate intent codes for cifti outputs
  .circleci/tests/test_ALFF.py
  xcp_d/interfaces/resting_state.py
  xcp_d/interfaces/workbench.py
  xcp_d/utils/filemanip.py
  xcp_d/utils/write_save.py
  xcp_d/workflow/postprocessing.py
  xcp_d/workflow/restingstate.py
Labels: bug

#705 Update README.rst
  README.rst
Labels: documentation, ignore-for-release

#697 Enable non-aggressive denoising with signal regressors
  docs/conf.py
  docs/generalworkflow.rst
  docs/usage.rst
  xcp_d/data/boilerplate.bib
  xcp_d/interfaces/regression.py
  xcp_d/utils/bids.py
  xcp_d/utils/confounds.py
  xcp_d/utils/utils.py
  xcp_d/workflow/base.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
Labels: enhancement

#703 Attempt to ingress HCP data into XCP
  docs/workflows.rst
  xcp_d/cli/run.py
  xcp_d/interfaces/report_core.py
  xcp_d/utils/bids.py
  xcp_d/utils/hcp2fmriprep.py
  xcp_d/workflow/anatomical.py
  xcp_d/workflow/base.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
Labels: bug, ignore-for-release

#713 Only concatenate processed runs
  xcp_d/utils/concatenation.py
Labels: bug

#712 Do not use downcasted files as name sources
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
  xcp_d/workflow/plotting.py
Labels: bug

#698 Use ds001491 fMRIPrep derivatives for tests
  .circleci/CiftiWithFreeSurferTest.sh
  .circleci/Nibabies.sh
  .circleci/NiftiWithFreeSurferTest.sh
  .circleci/NiftiWithoutFreeSurferTest.sh
  .circleci/RunPyTests.sh
  .circleci/cifti_with_freesurfer_outputs.txt
  .circleci/config.yml
  .circleci/get_data.sh
  .circleci/nifti_with_freesurfer_outputs.txt
  .circleci/test_affines.py
  .circleci/tests/conftest.py
  .circleci/tests/data/ds001419-fmriprep_cifti_filter.json
  .circleci/tests/data/ds001419-fmriprep_nifti_filter.json
  .circleci/tests/test_ALFF.py
  .circleci/tests/test_FD.py
  .circleci/tests/test_Reg.py
  .circleci/tests/test_TR.py
  .circleci/tests/test_confounds.py
  .circleci/tests/test_conn.py
  .circleci/tests/test_despike.py
  .circleci/tests/test_interpolation.py
  .circleci/tests/test_prepostcleaning.py
  .circleci/tests/test_reho.py
  .circleci/tests/test_smoothing.py
  .circleci/tests/test_utils_write_save.py
  xcp_d/data/nipreps.json
  xcp_d/workflow/anatomical.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
  xcp_d/workflow/execsummary.py
Labels: testing

#719 Improve identification of FreeSurfer derivatives
  xcp_d/utils/bids.py
  xcp_d/workflow/anatomical.py
  xcp_d/workflow/execsummary.py
Labels: bug, enhancement

#727 Warp segmentation file to appropriate space for carpet plots
  xcp_d/workflow/execsummary.py
  xcp_d/workflow/plotting.py
Labels: bug

#730 Add tests for confound loading function
  .circleci/tests/test_confounds.py
Labels: testing

#731 Collect preprocessed surfaces in new function
  xcp_d/utils/bids.py
  xcp_d/workflow/base.py
Labels: enhancement

#721 Refactor executive summary workflow
  xcp_d/interfaces/surfplotting.py
  xcp_d/utils/bids.py
  xcp_d/utils/plot.py
  xcp_d/workflow/base.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
  xcp_d/workflow/execsummary.py
  xcp_d/workflow/plotting.py
Labels: refactor

#733 Use brain mask in NIFTI connectivity workflow
  .circleci/tests/test_conn.py
  xcp_d/interfaces/connectivity.py
  xcp_d/utils/fcon.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/connectivity.py
Labels: bug

#732 Track start of workflow with sentry
  xcp_d/cli/run.py
Labels: maintenance

#736 Prepare for 0.3.1 release
  CITATION.cff
  xcp_d/cli/run.py
Labels: maintenance, ignore-for-release

#737 Replace CiftiDespike with connected nodes
  .circleci/tests/test_despike.py
  docs/api.rst
  xcp_d/interfaces/regression.py
  xcp_d/interfaces/resting_state.py
  xcp_d/interfaces/workbench.py
  xcp_d/utils/write_save.py
  xcp_d/workflow/cifti.py
Labels: refactor
