Repository PennLINC/xcp_d, pull requests merged in 2023-06, with the labels that each got.

#882 Update docs
  docs/usage.rst
  docs/workflows.rst
  xcp_d/interfaces/nilearn.py
  xcp_d/utils/doc.py
Labels: documentation

#889 Clean up testing framework and documentation
  .circleci/CiftiWithFreeSurferTest.sh
  .circleci/Nibabies.sh
  .circleci/NiftiWithFreeSurferTest.sh
  .circleci/NiftiWithoutFreeSurferTest.sh
  .circleci/RunPyTests.sh
  .circleci/config.yml
  .circleci/get_data.py
  .circleci/get_data.sh
  .circleci/test_affines.py
  .gitignore
  CHANGES.md
  docs/changes.rst
  docs/contributing.rst
  docs/dev_guide.rst
  docs/index.rst
  xcp_d/tests/run_local_tests.py
  xcp_d/tests/utils.py
Labels: documentation, testing

#890 Fix tests
  .circleci/config.yml
  xcp_d/tests/conftest.py
  xcp_d/tests/test_cli.py
  xcp_d/tests/test_despike.py
  xcp_d/tests/utils.py
Labels: testing, ignore-for-release

#893 Add contributing documentation
  CODE_OF_CONDUCT.md
  docs/contributing.rst
Labels: documentation

#839 Parcellate ReHo, ALFF, and surface morphometric maps
  docs/outputs.rst
  xcp_d/cli/combineqc.py
  xcp_d/data/xcp_d_bids_config.json
  xcp_d/interfaces/concatenation.py
  xcp_d/interfaces/connectivity.py
  xcp_d/interfaces/nilearn.py
  xcp_d/interfaces/workbench.py
  xcp_d/tests/conftest.py
  xcp_d/tests/data/test_ds001419_cifti_outputs.txt
  xcp_d/tests/data/test_ds001419_cifti_t2wonly_outputs.txt
  xcp_d/tests/data/test_ds001419_nifti_outputs.txt
  xcp_d/tests/data/test_fmriprep_without_freesurfer_outputs.txt
  xcp_d/tests/data/test_nibabies_outputs.txt
  xcp_d/tests/test_cli.py
  xcp_d/tests/test_interfaces_concatenation.py
  xcp_d/tests/test_workflows_connectivity.py
  xcp_d/utils/bids.py
  xcp_d/utils/utils.py
  xcp_d/workflows/anatomical.py
  xcp_d/workflows/base.py
  xcp_d/workflows/bold.py
  xcp_d/workflows/cifti.py
  xcp_d/workflows/concatenation.py
  xcp_d/workflows/connectivity.py
  xcp_d/workflows/outputs.py
  xcp_d/workflows/plotting.py
Labels: enhancement

#896 Update changelog and CFF file for 0.4.0
  CHANGES.md
  CITATION.cff
Labels: documentation

#897 Change packaging to use hatch-vcs and pyproject.toml
  .circleci/config.yml
  .codespellrc
  .git_archival.txt
  .gitattributes
  .github/workflows/lint.yml
  .gitignore
  .pre-commit-config.yaml
  .versions.json
  MANIFEST.in
  get_version.py
  pyproject.toml
  setup.cfg
  setup.py
  versioneer.py
  xcp_d/__about__.py
  xcp_d/__init__.py
  xcp_d/__main__.py
  xcp_d/_version.py
Labels: maintenance

#898 Fix description of signal denoising method in docs
  .circleci/config.yml
  docs/changes.md
  docs/changes.rst
  docs/conf.py
  docs/usage.rst
  xcp_d/workflows/connectivity.py
Labels: documentation

#900 Improve QC sidecar contents
  xcp_d/data/boilerplate.bib
  xcp_d/interfaces/plotting.py
  xcp_d/utils/qcmetrics.py
  xcp_d/workflows/plotting.py
Labels: documentation

#902 Rename the parcellated ALFF/ReHo outputs
  docs/outputs.rst
  xcp_d/data/xcp_d_bids_config.json
  xcp_d/tests/data/test_ds001419_cifti_outputs.txt
  xcp_d/tests/data/test_ds001419_cifti_t2wonly_outputs.txt
  xcp_d/tests/data/test_ds001419_nifti_outputs.txt
  xcp_d/tests/data/test_fmriprep_without_freesurfer_outputs.txt
  xcp_d/tests/data/test_nibabies_outputs.txt
  xcp_d/workflows/outputs.py
Labels: refactor

#910 Add tests for xcp_d.utils.utils module
  xcp_d/tests/test_utils_doc.py
  xcp_d/tests/test_utils_utils.py
Labels: testing

#912 Add tests for xcp_d.utils.execsummary module
  xcp_d/tests/test_utils_execsummary.py
  xcp_d/tests/test_utils_utils.py
  xcp_d/utils/utils.py
Labels: testing

#879 Add "none" option for denoising
  docs/workflows.rst
  xcp_d/cli/run.py
  xcp_d/interfaces/censoring.py
  xcp_d/interfaces/nilearn.py
  xcp_d/tests/data/test_ds001419_cifti_t2wonly_outputs.txt
  xcp_d/tests/test_cli.py
  xcp_d/tests/test_confounds.py
  xcp_d/tests/test_interfaces_censoring.py
  xcp_d/tests/test_utils_utils.py
  xcp_d/utils/confounds.py
  xcp_d/utils/utils.py
  xcp_d/workflows/outputs.py
  xcp_d/workflows/postprocessing.py
Labels: enhancement, dcan

#885 Add `--exact-time` parameter
  docs/outputs.rst
  docs/workflows.rst
  xcp_d/cli/run.py
  xcp_d/data/boilerplate.bib
  xcp_d/interfaces/censoring.py
  xcp_d/interfaces/connectivity.py
  xcp_d/interfaces/plotting.py
  xcp_d/tests/data/test_ds001419_nifti_outputs.txt
  xcp_d/tests/test_cli.py
  xcp_d/tests/test_interfaces_censoring.py
  xcp_d/tests/test_utils_utils.py
  xcp_d/tests/test_workflows_connectivity.py
  xcp_d/utils/confounds.py
  xcp_d/utils/doc.py
  xcp_d/utils/plotting.py
  xcp_d/utils/utils.py
  xcp_d/workflows/base.py
  xcp_d/workflows/bold.py
  xcp_d/workflows/cifti.py
  xcp_d/workflows/connectivity.py
  xcp_d/workflows/outputs.py
  xcp_d/workflows/postprocessing.py
Labels: enhancement, dcan, needs response

#913 Expand tests
  xcp_d/cli/parser_utils.py
  xcp_d/interfaces/plotting.py
  xcp_d/tests/conftest.py
  xcp_d/tests/test_cli.py
  xcp_d/tests/test_utils_bids.py
  xcp_d/tests/test_workflows_execsummary.py
  xcp_d/tests/utils.py
  xcp_d/utils/bids.py
  xcp_d/utils/modified_data.py
  xcp_d/workflows/execsummary.py
Labels: testing

#899 Allow white matter surface suffix to be either "_smoothwm" or "_white"
  xcp_d/utils/bids.py
Labels: enhancement, dcan

#916 Standardize executive summary carpet if params is "none"
  xcp_d/tests/test_utils_plotting.py
  xcp_d/workflows/base.py
  xcp_d/workflows/bold.py
  xcp_d/workflows/cifti.py
  xcp_d/workflows/concatenation.py
  xcp_d/workflows/plotting.py
Labels: bug

#918 Test CLI parameter validation
  xcp_d/cli/run.py
  xcp_d/tests/test_cli_run.py
Labels: refactor, testing

#917 Refactor collection functions
  xcp_d/tests/test_utils_bids.py
  xcp_d/utils/bids.py
  xcp_d/workflows/base.py
Labels: refactor
