Repository PennLINC/xcp_d, pull requests merged in 2023-01, with the labels that each got.

#702 Adopt executive summary's brainsprite using jinja templates
  .circleci/NiftiWithFreeSurferTest.sh
  .circleci/NiftiWithoutFreeSurferTest.sh
  .circleci/nifti_with_freesurfer_outputs.txt
  .circleci/nifti_without_freesurfer_outputs.txt
  .gitignore
  docs/output.rst
  setup.cfg
  xcp_d/data/executive_summary_scenes/brainsprite_template.scene.gz
  xcp_d/data/executive_summary_scenes/pngs_template.scene.gz
  xcp_d/data/executive_summary_templates/anatomical_registration_plots.html.jinja
  xcp_d/data/executive_summary_templates/brainsprite.js
  xcp_d/data/executive_summary_templates/brainsprite_with_pngs.html.jinja
  xcp_d/data/executive_summary_templates/concatenated_task_static_plots.html.jinja
  xcp_d/data/executive_summary_templates/cyclers.html.jinja
  xcp_d/data/executive_summary_templates/executive_summary.html.jinja
  xcp_d/data/executive_summary_templates/macros.html.jinja
  xcp_d/data/executive_summary_templates/task_static_plots.html.jinja
  xcp_d/data/reports.yml
  xcp_d/interfaces/constants.py
  xcp_d/interfaces/layout_builder.py
  xcp_d/interfaces/report.py
  xcp_d/interfaces/report_core.py
  xcp_d/interfaces/surfplotting.py
  xcp_d/interfaces/workbench.py
  xcp_d/utils/bids.py
  xcp_d/utils/execsummary.py
  xcp_d/utils/utils.py
  xcp_d/workflow/anatomical.py
  xcp_d/workflow/base.py
  xcp_d/workflow/execsummary.py
Labels: enhancement

#744 Change secret keys for deploying to DockerHub
  .circleci/config.yml
Labels: maintenance, ignore-for-release

#745 Prepare for 0.3.2 release
  CITATION.cff
Labels: maintenance, ignore-for-release

#748 Pin networkx version
  setup.cfg
Labels: maintenance, ignore-for-release

#752 Fix CIFTI downcasting test
  .circleci/tests/test_prepostcleaning.py
Labels: testing

#743 Replace missing vertices' values with NaNs
  .circleci/tests/test_conn.py
  .circleci/tests/test_prepostcleaning.py
  xcp_d/interfaces/prepostcleaning.py
  xcp_d/interfaces/workbench.py
  xcp_d/workflow/connectivity.py
Labels: bug

#755 Change default highpass filter cutoff from 0.009 to 0.01
  .circleci/tests/test_ALFF.py
  docs/generalworkflow.rst
  docs/output.rst
  xcp_d/cli/run.py
  xcp_d/workflow/base.py
  xcp_d/workflow/execsummary.py
  xcp_d/workflow/restingstate.py
Labels: breaking-change

#740 Use pytest to test command-line interface
  .circleci/RunPyTests.sh
  .circleci/config.yml
  docs/usage.rst
  pyproject.toml
  setup.cfg
  xcp_d/cli/parser_utils.py
  xcp_d/cli/run.py
  xcp_d/interfaces/report_core.py
  xcp_d/tests/__init__.py
  xcp_d/tests/conftest.py
  xcp_d/tests/data/band_passed_bold_data.txt
  xcp_d/tests/data/ds001419-fmriprep_cifti_filter.json
  xcp_d/tests/data/ds001419-fmriprep_cifti_outputs.txt
  xcp_d/tests/data/ds001419-fmriprep_nifti_filter.json
  xcp_d/tests/data/ds001419-fmriprep_nifti_outputs.txt
  xcp_d/tests/data/license.txt
  xcp_d/tests/data/low_passed_MR_data.txt
  xcp_d/tests/data/nibabies_outputs.txt
  xcp_d/tests/data/nifti_without_freesurfer_outputs.txt
  xcp_d/tests/data/notched_MR_data.txt
  xcp_d/tests/data/raw_data.txt
  xcp_d/tests/test_ALFF.py
  xcp_d/tests/test_FD.py
  xcp_d/tests/test_Reg.py
  xcp_d/tests/test_TR.py
  xcp_d/tests/test_cli.py
  xcp_d/tests/test_confounds.py
  xcp_d/tests/test_conn.py
  xcp_d/tests/test_despike.py
  xcp_d/tests/test_filtering.py
  xcp_d/tests/test_interpolation.py
  xcp_d/tests/test_prepostcleaning.py
  xcp_d/tests/test_reho.py
  xcp_d/tests/test_smoothing.py
  xcp_d/tests/test_utils.py
  xcp_d/tests/test_utils_write_save.py
  xcp_d/tests/utils.py
  xcp_d/utils/concatenation.py
Labels: testing

#758 Upload coverage reports to CodeCov
  .circleci/config.yml
Labels: testing, maintenance

#760 Add CodeCov badge to README
  README.rst
Labels: documentation, ignore-for-release

#706 Refactor anatomical workflow
  xcp_d/interfaces/utils.py
  xcp_d/tests/data/ds001419-fmriprep_cifti_outputs.txt
  xcp_d/tests/data/ds001419-fmriprep_nifti_outputs.txt
  xcp_d/utils/bids.py
  xcp_d/utils/execsummary.py
  xcp_d/workflow/anatomical.py
  xcp_d/workflow/base.py
  xcp_d/workflow/execsummary.py
Labels: enhancement, refactor, breaking-change

#759 Select MNI152NLin6Asym target space for T1w from CIFTI derivatives
  xcp_d/data/nipreps.json
  xcp_d/tests/data/ds001419-fmriprep_nifti_outputs.txt
  xcp_d/tests/data/nibabies_outputs.txt
  xcp_d/tests/data/nifti_without_freesurfer_outputs.txt
  xcp_d/tests/test_utils_bids.py
  xcp_d/utils/bids.py
  xcp_d/workflow/anatomical.py
  xcp_d/workflow/base.py
Labels: bug

#761 Link to `xcp_d-examples` in documentation
  docs/usage.rst
Labels: documentation

#754 Add option to estimate brain radius from brain mask
  .circleci/Nibabies.sh
  .circleci/NiftiWithoutFreeSurferTest.sh
  docs/output.rst
  xcp_d/cli/parser_utils.py
  xcp_d/cli/run.py
  xcp_d/interfaces/prepostcleaning.py
  xcp_d/tests/data/ds001419-fmriprep_cifti_outputs.txt
  xcp_d/tests/data/ds001419-fmriprep_nifti_outputs.txt
  xcp_d/tests/data/nibabies_outputs.txt
  xcp_d/tests/data/nifti_without_freesurfer_outputs.txt
  xcp_d/tests/test_cli.py
  xcp_d/tests/test_utils.py
  xcp_d/tests/test_utils_utils.py
  xcp_d/utils/doc.py
  xcp_d/utils/utils.py
  xcp_d/workflow/base.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
  xcp_d/workflow/outputs.py
  xcp_d/workflow/plotting.py
Labels: enhancement

#763 Fix typos in documentation
  docs/api.rst
  xcp_d/workflow/anatomical.py
Labels: documentation, ignore-for-release

#753 Do not require `--combineruns` to generate DCAN QC files
  docs/output.rst
  xcp_d/data/nipreps.json
  xcp_d/tests/data/ds001419-fmriprep_cifti_outputs.txt
  xcp_d/tests/data/nifti_without_freesurfer_outputs.txt
  xcp_d/utils/concatenation.py
  xcp_d/utils/execsummary.py
  xcp_d/utils/qcmetrics.py
  xcp_d/workflow/plotting.py
Labels: enhancement, breaking-change

#762 Change QC filenames and fix `xcp_d-combineqc` command-line interface
  xcp_d/cli/combineqc.py
  xcp_d/tests/data/ds001419-fmriprep_cifti_outputs.txt
  xcp_d/tests/data/ds001419-fmriprep_nifti_outputs.txt
  xcp_d/tests/data/nibabies_outputs.txt
  xcp_d/tests/data/nifti_without_freesurfer_outputs.txt
  xcp_d/tests/test_cli.py
  xcp_d/workflow/outputs.py
Labels: bug, testing, breaking-change

#766 Only generate brainsprite figures when the `--dcan_qc` flag is used
  xcp_d/workflow/base.py
Labels: bug

#769 Retain cohort entity in derivative filenames
  xcp_d/data/nipreps.json
  xcp_d/tests/data/nibabies_outputs.txt
  xcp_d/workflow/outputs.py
Labels: bug, breaking-change

#647 Output warped atlases to derivatives
  setup.cfg
  xcp_d/data/nipreps.json
  xcp_d/interfaces/bids.py
  xcp_d/tests/data/ds001419-fmriprep_cifti_outputs.txt
  xcp_d/tests/data/ds001419-fmriprep_nifti_outputs.txt
  xcp_d/tests/data/nibabies_outputs.txt
  xcp_d/tests/data/nifti_without_freesurfer_outputs.txt
  xcp_d/tests/test_conn.py
  xcp_d/tests/test_utils_modified_data.py
  xcp_d/tests/utils.py
  xcp_d/utils/modified_data.py
  xcp_d/workflow/bold.py
  xcp_d/workflow/cifti.py
  xcp_d/workflow/connectivity.py
Labels: enhancement

#771 Show workflow test logs live
  .circleci/config.yml
  docs/output.rst
  xcp_d/interfaces/qc_plot.py
Labels: documentation, testing, ignore-for-release

#772 Add information about preprocessing requirements
  docs/usage.rst
Labels: documentation

#778 Rename `workflow` module to `workflows`
  docs/api.rst
  xcp_d/cli/run.py
  xcp_d/tests/test_ALFF.py
  xcp_d/tests/test_conn.py
  xcp_d/tests/test_reho.py
  xcp_d/workflows/__init__.py
  xcp_d/workflows/anatomical.py
  xcp_d/workflows/base.py
  xcp_d/workflows/bold.py
  xcp_d/workflows/cifti.py
  xcp_d/workflows/connectivity.py
  xcp_d/workflows/execsummary.py
  xcp_d/workflows/outputs.py
  xcp_d/workflows/plotting.py
  xcp_d/workflows/postprocessing.py
  xcp_d/workflows/restingstate.py
Labels: refactor, ignore-for-release

#770 Require the `--cifti` flag in order to use `--warp-surfaces-native2std`
  docs/usage.rst
  xcp_d/cli/run.py
  xcp_d/tests/data/ds001419-fmriprep_nifti_outputs.txt
  xcp_d/tests/test_cli.py
  xcp_d/workflows/base.py
Labels: breaking-change

#780 Remove unused BrainPlot interface
  xcp_d/interfaces/resting_state.py
  xcp_d/utils/modified_data.py
  xcp_d/utils/plot.py
  xcp_d/utils/utils.py
  xcp_d/utils/write_save.py
Labels: refactor, ignore-for-release

#757 Zero out parcels with <50% coverage
  docs/output.rst
  xcp_d/data/nipreps.json
  xcp_d/interfaces/connectivity.py
  xcp_d/interfaces/prepostcleaning.py
  xcp_d/interfaces/workbench.py
  xcp_d/tests/data/ds001419-fmriprep_cifti_outputs.txt
  xcp_d/tests/data/ds001419-fmriprep_nifti_outputs.txt
  xcp_d/tests/data/nibabies_outputs.txt
  xcp_d/tests/data/nifti_without_freesurfer_outputs.txt
  xcp_d/tests/test_conn.py
  xcp_d/tests/test_prepostcleaning.py
  xcp_d/tests/test_workflows_connectivity.py
  xcp_d/utils/fcon.py
  xcp_d/utils/write_save.py
  xcp_d/workflows/bold.py
  xcp_d/workflows/cifti.py
  xcp_d/workflows/connectivity.py
  xcp_d/workflows/outputs.py
Labels: enhancement, breaking-change
