Repository PennLINC/xcp_d, pull requests merged in 2023-04, with the labels that each got.

#838 Support preprocessing derivatives with T2w, but no T1w
  .circleci/config.yml
  docs/usage.rst
  pyproject.toml
  xcp_d/interfaces/concatenation.py
  xcp_d/interfaces/plotting.py
  xcp_d/interfaces/utils.py
  xcp_d/tests/conftest.py
  xcp_d/tests/data/ds001419-fmriprep_cifti_t2wonly_filter.json
  xcp_d/tests/data/ds001419-fmriprep_cifti_t2wonly_outputs.txt
  xcp_d/tests/test_cli.py
  xcp_d/tests/test_interfaces_concatenation.py
  xcp_d/tests/test_utils_bids.py
  xcp_d/tests/test_workflows_anatomical.py
  xcp_d/tests/test_workflows_connectivity.py
  xcp_d/utils/bids.py
  xcp_d/utils/doc.py
  xcp_d/utils/qcmetrics.py
  xcp_d/utils/utils.py
  xcp_d/workflows/anatomical.py
  xcp_d/workflows/base.py
  xcp_d/workflows/bold.py
  xcp_d/workflows/cifti.py
  xcp_d/workflows/concatenation.py
  xcp_d/workflows/connectivity.py
  xcp_d/workflows/execsummary.py
  xcp_d/workflows/plotting.py
Labels: enhancement

#851 Work around load_confounds aCompCor bug
  setup.cfg
  xcp_d/tests/test_confounds.py
  xcp_d/utils/confounds.py
  xcp_d/workflows/postprocessing.py
Labels: bug

#850 Remove codecov dependency
  .circleci/config.yml
  Dockerfile
  README.rst
Labels: testing

#854 Change FD Threshold from 0.2 to 0.3
  xcp_d/_version.py
  xcp_d/cli/run.py
  xcp_d/interfaces/censoring.py
  xcp_d/tests/test_FD.py
  xcp_d/tests/test_cli.py
  xcp_d/tests/test_interfaces_nilearn.py
  xcp_d/tests/test_utils_utils.py
  xcp_d/workflows/base.py
  xcp_d/workflows/bold.py
  xcp_d/workflows/cifti.py
  xcp_d/workflows/outputs.py
  xcp_d/workflows/postprocessing.py
Labels: breaking-change

#861 Allow for smoothing to be zero
  xcp_d/tests/data/nibabies_outputs.txt
  xcp_d/tests/test_cli.py
  xcp_d/workflows/postprocessing.py
Labels: bug

#857 Add boilerplate to the executive summary
  xcp_d/data/executive_summary_templates/executive_summary.html.jinja
  xcp_d/interfaces/execsummary.py
Labels: documentation

#862 Support high-pass or low-pass only filtering
  xcp_d/cli/run.py
  xcp_d/tests/test_cli.py
  xcp_d/utils/doc.py
  xcp_d/utils/utils.py
  xcp_d/workflows/outputs.py
  xcp_d/workflows/postprocessing.py
Labels: enhancement
