Repository PennLINC/xcp_d, pull requests merged in 2024-02, with the labels that each got.

#1056 Make description of `smoothing` parameter clearer when set to `0`
  xcp_d/cli/run.py
Labels: documentation

#1060 Address bug with T2w-only processing
  xcp_d/tests/test_cli.py
  xcp_d/tests/utils.py
  xcp_d/utils/bids.py
Labels: bug

#1063 Use strict file-matching in collect_run_data
  xcp_d/utils/bids.py
Labels: bug

#1066 Fix potential atlas file race condition
  xcp_d/utils/atlas.py
Labels: bug

#1068 Make "DatasetType" key recommended, not required
  xcp_d/utils/bids.py
  xcp_d/workflows/connectivity.py
Labels: enhancement

#1071 Do not warn if `fd-thresh` and `min-time` are both set to 0
  xcp_d/cli/run.py
Labels: bug

#1070 Add release notes for releases 0.6.1 and 0.6.2
  docs/changes.md
Labels: documentation

#1073 Use `copy_atlas` to write out atlas tsv and json files
  xcp_d/tests/test_utils_atlas.py
  xcp_d/utils/atlas.py
  xcp_d/workflows/connectivity.py
Labels: bug

#1072 Raise error if FS_LICENSE environment variable is not an existing file
  xcp_d/cli/run.py
  xcp_d/tests/test_cli_run.py
  xcp_d/tests/utils.py
Labels: bug
