Repository PennLINC/xcp_d, pull requests merged in 2024-03, with the labels that each got.

#1078 Generate T2w executive summary plots when T1w is also available
  xcp_d/workflows/execsummary.py
Labels: bug

#1079 Update changelog for 0.6.3
  CITATION.cff
  docs/changes.md
Labels: documentation

#1075 Raise error if atlas affines don't match across participants
  xcp_d/interfaces/bids.py
  xcp_d/tests/test_interfaces_bids.py
  xcp_d/tests/test_utils_atlas.py
  xcp_d/utils/atlas.py
  xcp_d/utils/bids.py
  xcp_d/workflows/connectivity.py
Labels: bug

#1088 Replace `bids:xcp_d:` BIDS URI with `bids::`
  xcp_d/tests/test_utils_bids.py
  xcp_d/utils/bids.py
Labels: enhancement

#1092 Fix query error report in `collect_mesh_data`
  xcp_d/cli/run.py
  xcp_d/interfaces/execsummary.py
  xcp_d/tests/test_utils_bids.py
  xcp_d/tests/utils.py
  xcp_d/utils/bids.py
Labels: bug

#1087 Adopt Lindquist-compliant denoising method
  docs/outputs.rst
  docs/workflows.rst
  xcp_d/data/boilerplate.bib
  xcp_d/interfaces/censoring.py
  xcp_d/interfaces/concatenation.py
  xcp_d/interfaces/nilearn.py
  xcp_d/interfaces/plotting.py
  xcp_d/tests/test_confounds.py
  xcp_d/tests/test_interfaces_censoring.py
  xcp_d/tests/test_interfaces_concatenation.py
  xcp_d/tests/test_interfaces_nilearn.py
  xcp_d/tests/test_utils_plotting.py
  xcp_d/tests/test_utils_utils.py
  xcp_d/utils/confounds.py
  xcp_d/utils/doc.py
  xcp_d/utils/plotting.py
  xcp_d/utils/utils.py
  xcp_d/utils/write_save.py
  xcp_d/workflows/base.py
  xcp_d/workflows/bold.py
  xcp_d/workflows/cifti.py
  xcp_d/workflows/concatenation.py
  xcp_d/workflows/outputs.py
  xcp_d/workflows/plotting.py
  xcp_d/workflows/postprocessing.py
Labels: bug

#1086 [DCAN] Enable DCAN QC by default
  docs/outputs.rst
  docs/workflows.rst
  xcp_d/cli/run.py
  xcp_d/tests/test_cli.py
  xcp_d/workflows/base.py
Labels: deprecation, dcan

#1095 Prepare for 0.6.4 release
  .versions.json
  CITATION.cff
  docs/changes.md
Labels: maintenance, ignore-for-release

#1096 [DCAN] Remove `--dcan-qc` parameter
  xcp_d/cli/run.py
Labels: breaking-change, dcan

#1065 Bring outputs up to date with BEPs 11, 12, 17, and 38
  docs/outputs.rst
  docs/usage.rst
  xcp_d/cli/combineqc.py
  xcp_d/data/xcp_d_bids_config.json
  xcp_d/interfaces/bids.py
  xcp_d/interfaces/plotting.py
  xcp_d/interfaces/report.py
  xcp_d/tests/data/test_ds001419_cifti_outputs.txt
  xcp_d/tests/data/test_ds001419_nifti_outputs.txt
  xcp_d/tests/data/test_fmriprep_without_freesurfer_outputs.txt
  xcp_d/tests/data/test_nibabies_outputs.txt
  xcp_d/tests/data/test_pnc_cifti_outputs.txt
  xcp_d/tests/data/test_pnc_cifti_t2wonly_outputs.txt
  xcp_d/tests/data/test_ukbiobank_outputs.txt
  xcp_d/tests/test_interfaces_bids.py
  xcp_d/tests/test_utils_bids.py
  xcp_d/utils/bids.py
  xcp_d/workflows/base.py
  xcp_d/workflows/concatenation.py
  xcp_d/workflows/connectivity.py
  xcp_d/workflows/outputs.py
Labels: breaking-change

#1097 Add information about ReHo to read-the-docs
  docs/workflows.rst
Labels: documentation

#1091 Create reformatted BrainSwipes figures for HBCD QC
  .circleci/config.yml
  xcp_d/interfaces/execsummary.py
  xcp_d/interfaces/plotting.py
  xcp_d/tests/test_cli.py
  xcp_d/workflows/execsummary.py
Labels: enhancement, dcan

#1102 Prepare for 0.7.0 release
  CITATION.cff
  docs/changes.md
Labels: maintenance, ignore-for-release

#1040 Adopt Nipreps-style Config object
  .circleci/config.yml
  docs/usage.rst
  pyproject.toml
  xcp_d/__main__.py
  xcp_d/_warnings.py
  xcp_d/cli/parser.py
  xcp_d/cli/run.py
  xcp_d/cli/version.py
  xcp_d/cli/workflow.py
  xcp_d/config.py
  xcp_d/data/__init__.py
  xcp_d/data/reports-spec.yml
  xcp_d/ingression/abcdbids.py
  xcp_d/ingression/hcpya.py
  xcp_d/ingression/ukbiobank.py
  xcp_d/interfaces/execsummary.py
  xcp_d/interfaces/report_core.py
  xcp_d/tests/conftest.py
  xcp_d/tests/data/config.toml
  xcp_d/tests/data/test_ds001419_cifti_outputs.txt
  xcp_d/tests/data/test_ds001419_nifti_outputs.txt
  xcp_d/tests/data/test_fmriprep_without_freesurfer_outputs.txt
  xcp_d/tests/data/test_nibabies_outputs.txt
  xcp_d/tests/data/test_pnc_cifti_outputs.txt
  xcp_d/tests/data/test_pnc_cifti_t2wonly_outputs.txt
  xcp_d/tests/data/test_ukbiobank_outputs.txt
  xcp_d/tests/test_cli.py
  xcp_d/tests/test_cli_run.py
  xcp_d/tests/test_utils_bids.py
  xcp_d/tests/test_workflows_anatomical.py
  xcp_d/tests/test_workflows_connectivity.py
  xcp_d/tests/test_workflows_restingstate.py
  xcp_d/tests/tests.py
  xcp_d/tests/utils.py
  xcp_d/utils/bids.py
  xcp_d/utils/confounds.py
  xcp_d/utils/sentry.py
  xcp_d/utils/utils.py
  xcp_d/workflows/anatomical.py
  xcp_d/workflows/base.py
  xcp_d/workflows/bold.py
  xcp_d/workflows/cifti.py
  xcp_d/workflows/concatenation.py
  xcp_d/workflows/connectivity.py
  xcp_d/workflows/execsummary.py
  xcp_d/workflows/outputs.py
  xcp_d/workflows/plotting.py
  xcp_d/workflows/postprocessing.py
  xcp_d/workflows/restingstate.py
Labels: refactor, maintenance

#1103 Investigate test failures
  xcp_d/tests/test_utils_confounds.py
Labels: ignore-for-release

#1107 Use pytest-env to capture warnings on CI runs
  pyproject.toml
  xcp_d/config.py
Labels: testing

#1112 Convert coverage values to float32 to address pandas warning
  xcp_d/interfaces/connectivity.py
Labels: refactor

#1115 Change default `--min-time` from 100 to 240
  xcp_d/cli/parser.py
  xcp_d/config.py
  xcp_d/tests/test_cli.py
Labels: breaking-change

#1116 Add `--bids-database-dir` parameter
  xcp_d/cli/parser.py
  xcp_d/config.py
  xcp_d/tests/tests.py
Labels: enhancement

#1114 Modify metadata and boilerplate to reflect updated motion filter parameters
  xcp_d/interfaces/censoring.py
  xcp_d/tests/test_utils_confounds.py
  xcp_d/utils/confounds.py
  xcp_d/utils/modified_data.py
  xcp_d/workflows/bold.py
  xcp_d/workflows/cifti.py
  xcp_d/workflows/postprocessing.py
  xcp_d/workflows/restingstate.py
Labels: bug, documentation
