Repository PennLINC/xcp_d, pull requests merged in 2024-09, with the labels that each got.

#1248 Change linc mode default file format to CIFTI
  docs/workflows.rst
  xcp_d/cli/parser.py
  xcp_d/tests/test_cli.py
  xcp_d/tests/test_cli_run.py
Labels: breaking-change

#1190 Stop ingressing anatomical-space tissue segmentation file
  docs/outputs.rst
  docs/usage.rst
  docs/workflows.rst
  xcp_d/data/io_spec.yaml
  xcp_d/ingression/ukbiobank.py
  xcp_d/ingression/utils.py
  xcp_d/interfaces/utils.py
  xcp_d/tests/conftest.py
  xcp_d/tests/data/test_ds001419_cifti_outputs.txt
  xcp_d/tests/data/test_ds001419_nifti_outputs.txt
  xcp_d/tests/data/test_fmriprep_without_freesurfer_outputs.txt
  xcp_d/tests/data/test_nibabies_outputs.txt
  xcp_d/tests/data/test_pnc_cifti_outputs.txt
  xcp_d/tests/data/test_pnc_cifti_t2wonly_outputs.txt
  xcp_d/tests/data/test_ukbiobank_outputs.txt
  xcp_d/tests/test_workflows_anatomical.py
  xcp_d/utils/bids.py
  xcp_d/workflows/anatomical/volume.py
  xcp_d/workflows/base.py
Labels: breaking-change

#1249 Fix subject sphere query
  xcp_d/utils/bids.py
Labels: bug

#1250 Prepare for 0.9.0 release
  CITATION.cff
  docs/changes.md
Labels: maintenance, ignore-for-release

#1256 Remove n_procs for nodes that do not use multiple cores
  .circleci/config.yml
  pyproject.toml
  xcp_d/interfaces/workbench.py
  xcp_d/tests/test_cli.py
  xcp_d/tests/test_smoothing.py
  xcp_d/tests/test_workflows_anatomical.py
  xcp_d/tests/utils.py
  xcp_d/workflows/anatomical/parcellation.py
  xcp_d/workflows/anatomical/plotting.py
  xcp_d/workflows/anatomical/surface.py
  xcp_d/workflows/anatomical/volume.py
  xcp_d/workflows/bold/cifti.py
  xcp_d/workflows/bold/connectivity.py
  xcp_d/workflows/bold/metrics.py
  xcp_d/workflows/bold/nifti.py
  xcp_d/workflows/bold/plotting.py
  xcp_d/workflows/bold/postprocessing.py
  xcp_d/workflows/parcellation.py
Labels: refactor, testing

#1260 Replace internal data module with acres
  pyproject.toml
  xcp_d/data/__init__.py
Labels: refactor

#1261 Prepare for 0.9.1 release
  CITATION.cff
  docs/changes.md
Labels: maintenance, ignore-for-release

#1263 Don't rerun alff if num threads changes
  xcp_d/interfaces/restingstate.py
Labels: refactor

#1262 Remove xcp_d_dir and clean datasinks
  xcp_d/cli/parser.py
  xcp_d/cli/run.py
  xcp_d/cli/workflow.py
  xcp_d/config.py
  xcp_d/data/tests/config.toml
  xcp_d/tests/test_cli.py
  xcp_d/tests/test_workflows_anatomical.py
  xcp_d/tests/test_workflows_connectivity.py
  xcp_d/tests/test_workflows_metrics.py
  xcp_d/tests/test_workflows_plotting.py
  xcp_d/tests/tests.py
  xcp_d/workflows/anatomical/outputs.py
  xcp_d/workflows/anatomical/parcellation.py
  xcp_d/workflows/anatomical/plotting.py
  xcp_d/workflows/anatomical/surface.py
  xcp_d/workflows/anatomical/volume.py
  xcp_d/workflows/base.py
  xcp_d/workflows/bold/concatenation.py
  xcp_d/workflows/bold/connectivity.py
  xcp_d/workflows/bold/metrics.py
  xcp_d/workflows/bold/outputs.py
  xcp_d/workflows/bold/plotting.py
  xcp_d/workflows/bold/postprocessing.py
  xcp_d/workflows/parcellation.py
  xcp_d/workflows/plotting.py
Labels: refactor

#1267 Bump Docker deployment version
  .circleci/config.yml
Labels: maintenance, ignore-for-release

#1266 Add dataset links to config object
  xcp_d/cli/run.py
  xcp_d/config.py
  xcp_d/tests/test_cli.py
  xcp_d/tests/test_utils_bids.py
  xcp_d/utils/bids.py
Labels: refactor

#1271 Patch task_id into bids_filters
  xcp_d/config.py
  xcp_d/tests/data/ds001419_cifti_filter.json
  xcp_d/tests/test_cli.py
Labels: bug

#1255 Replace restricted confound sets with config files
  .circleci/config.yml
  docs/outputs.rst
  docs/usage.rst
  docs/workflows.rst
  xcp_d/cli/parser.py
  xcp_d/cli/parser_utils.py
  xcp_d/cli/run.py
  xcp_d/cli/workflow.py
  xcp_d/config.py
  xcp_d/data/nuisance/24P.yml
  xcp_d/data/nuisance/27P.yml
  xcp_d/data/nuisance/36P.yml
  xcp_d/data/nuisance/acompcor.yml
  xcp_d/data/nuisance/acompcor_gsr.yml
  xcp_d/data/nuisance/aroma.yml
  xcp_d/data/nuisance/aroma_gsr.yml
  xcp_d/data/nuisance/gsr_only.yml
  xcp_d/data/nuisance/rapidtide+24P.yml
  xcp_d/data/tests/config.toml
  xcp_d/interfaces/censoring.py
  xcp_d/interfaces/concatenation.py
  xcp_d/interfaces/nilearn.py
  xcp_d/interfaces/plotting.py
  xcp_d/interfaces/utils.py
  xcp_d/tests/conftest.py
  xcp_d/tests/data/ds001419_nifti_filter.json
  xcp_d/tests/data/test_ds001419_cifti_outputs.txt
  xcp_d/tests/data/test_ds001419_nifti_outputs.txt
  xcp_d/tests/data/test_pnc_cifti_outputs.txt
  xcp_d/tests/data/test_pnc_cifti_t2wonly_outputs.txt
  xcp_d/tests/data/test_ukbiobank_outputs.txt
  xcp_d/tests/test_TR.py
  xcp_d/tests/test_cli.py
  xcp_d/tests/test_cli_run.py
  xcp_d/tests/test_interfaces_censoring.py
  xcp_d/tests/test_interfaces_concatenation.py
  xcp_d/tests/test_interfaces_nilearn.py
  xcp_d/tests/test_utils_bids.py
  xcp_d/tests/test_utils_boilerplate.py
  xcp_d/tests/test_utils_confounds.py
  xcp_d/tests/test_utils_execsummary.py
  xcp_d/tests/test_utils_plotting.py
  xcp_d/tests/test_utils_utils.py
  xcp_d/tests/test_utils_write_save.py
  xcp_d/tests/utils.py
  xcp_d/utils/bids.py
  xcp_d/utils/boilerplate.py
  xcp_d/utils/confounds.py
  xcp_d/utils/doc.py
  xcp_d/utils/modified_data.py
  xcp_d/utils/plotting.py
  xcp_d/workflows/base.py
  xcp_d/workflows/bold/cifti.py
  xcp_d/workflows/bold/concatenation.py
  xcp_d/workflows/bold/connectivity.py
  xcp_d/workflows/bold/nifti.py
  xcp_d/workflows/bold/outputs.py
  xcp_d/workflows/bold/plotting.py
  xcp_d/workflows/bold/postprocessing.py
Labels: enhancement, breaking-change
