Repository PennLINC/xcp_d, pull requests merged in 2025-04, with the labels that each got.

#1425 Use masked functional and anatomical images for executive summary
  xcp_d/interfaces/nilearn.py
  xcp_d/utils/bids.py
  xcp_d/workflows/anatomical/plotting.py
  xcp_d/workflows/anatomical/volume.py
  xcp_d/workflows/base.py
  xcp_d/workflows/bold/cifti.py
  xcp_d/workflows/bold/nifti.py
  xcp_d/workflows/bold/plotting.py
Labels: enhancement, dcan

#1430 Prepare for 0.10.7 (second attempt)
  CITATION.cff
  docs/changes.md
Labels: maintenance, ignore-for-release

#1433 Ensure T1w-only processing does not collect T2w
  xcp_d/data/tests/skeletons/nibabies_ignore_t1w.yml
  xcp_d/data/tests/skeletons/nibabies_ignore_t2w.yml
  xcp_d/data/tests/skeletons/nibabies_no_t1w_t2w.yml
  xcp_d/data/tests/skeletons/nibabies_t1w_only.yml
  xcp_d/data/tests/skeletons/nibabies_t1wspace_t2w.yml
  xcp_d/data/tests/skeletons/nibabies_t2w_only.yml
  xcp_d/data/tests/skeletons/nibabies_t2wspace_t1w.yml
  xcp_d/tests/test_utils_bids.py
  xcp_d/utils/bids.py
Labels: bug

#1436 Add `--report-output-level` parameter
  docs/outputs.rst
  xcp_d/cli/parser.py
  xcp_d/cli/run.py
  xcp_d/cli/workflow.py
  xcp_d/config.py
  xcp_d/data/reports-spec.yml
  xcp_d/data/xcp_d_bids_config.json
  xcp_d/data/xcp_d_bids_config2.json
  xcp_d/interfaces/execsummary.py
  xcp_d/reports/core.py
  xcp_d/tests/data/test_ds001419_cifti_outputs.txt
  xcp_d/tests/data/test_fmriprep_without_freesurfer_outputs.txt
  xcp_d/tests/data/test_nibabies_outputs.txt
  xcp_d/tests/data/test_pnc_cifti_outputs.txt
  xcp_d/tests/test_cli.py
  xcp_d/tests/test_cli_run.py
Labels: enhancement

#1438 Support session-wise anatomical processing
  xcp_d/cli/parser.py
  xcp_d/cli/run.py
  xcp_d/cli/workflow.py
  xcp_d/config.py
  xcp_d/reports/core.py
  xcp_d/tests/test_cli.py
  xcp_d/workflows/base.py
Labels: bug

#1439 Fix session-wise collection
  xcp_d/data/tests/skeletons/nibabies_crosssectional.yml
  xcp_d/data/tests/skeletons/nibabies_longitudinal_one_to_all.yml
  xcp_d/data/tests/skeletons/nibabies_longitudinal_one_to_one.yml
  xcp_d/tests/test_utils_bids_collect_data.py
  xcp_d/utils/bids.py
  xcp_d/workflows/base.py
Labels: bug

#1440 Fix session-wise collection of surface files
  xcp_d/tests/test_utils_bids.py
  xcp_d/utils/bids.py
  xcp_d/workflows/base.py
Labels: bug

#1441 Make workflow name unique for session-wise processing
  xcp_d/workflows/base.py
Labels: bug

#1411 Add nifti brain mask to hcpya ingression
  xcp_d/ingression/hcpya.py
Labels: bug

#1417 Use `mem_mb` instead of `mem_gb`
  xcp_d/cli/parser.py
  xcp_d/cli/parser_utils.py
Labels: breaking-change
