Repository PennLINC/xcp_d, pull requests merged in 2025-01, with the labels that each got.

#1349 Clarify that warped surfaces can be overlaid on the MNI152NLin6Asym template
  docs/outputs.rst
  xcp_d/cli/parser.py
  xcp_d/workflows/anatomical/surface.py
Labels: documentation

#1357 Run ruff
  docs/conf.py
  xcp_d/__about__.py
  xcp_d/_warnings.py
  xcp_d/cli/parser.py
  xcp_d/cli/workflow.py
  xcp_d/config.py
  xcp_d/interfaces/censoring.py
  xcp_d/interfaces/execsummary.py
  xcp_d/interfaces/report.py
  xcp_d/interfaces/workbench.py
  xcp_d/tests/run_local_tests.py
  xcp_d/tests/utils.py
  xcp_d/utils/atlas.py
  xcp_d/utils/bids.py
  xcp_d/utils/boilerplate.py
  xcp_d/utils/modified_data.py
  xcp_d/utils/plotting.py
  xcp_d/utils/utils.py
  xcp_d/workflows/base.py
  xcp_d/workflows/parcellation.py
Labels: maintenance

#1359 Prepare for 0.10.2 release
  CITATION.cff
  docs/changes.md
Labels: maintenance, ignore-for-release

#1358 Downgrade connectome workbench version
  .circleci/config.yml
  Dockerfile
  xcp_d/tests/run_local_tests.py
Labels: bug

#1362 Fix resource class of CIFTI tests
  .circleci/config.yml
Labels: bug, testing

#1365 Support multi-step composite transforms from Nibabies
  xcp_d/interfaces/__init__.py
  xcp_d/interfaces/ants.py
  xcp_d/interfaces/c3.py
  xcp_d/interfaces/workbench.py
  xcp_d/tests/test_workflows_anatomical.py
  xcp_d/workflows/anatomical/plotting.py
  xcp_d/workflows/anatomical/surface.py
  xcp_d/workflows/base.py
Labels: bug

#1307 Track lost degrees of freedom
  docs/outputs.rst
  docs/workflows.rst
  xcp_d/cli/parser.py
  xcp_d/data/reports-spec-func.yml
  xcp_d/data/reports-spec.yml
  xcp_d/interfaces/report.py
  xcp_d/interfaces/utils.py
  xcp_d/utils/modified_data.py
  xcp_d/workflows/bold/cifti.py
  xcp_d/workflows/bold/nifti.py
  xcp_d/workflows/bold/plotting.py
Labels: enhancement

#1367 Prepare for 0.10.4 release
  CITATION.cff
  docs/changes.md
Labels: maintenance, ignore-for-release

#1369 Stop autoescaping the boilerplate
  xcp_d/data/executive_summary_templates/executive_summary.html.jinja
Labels: bug

#1368 Use trimesh to generate brainsprite
  .circleci/config.yml
  pyproject.toml
  xcp_d/data/executive_summary_scenes/brainsprite_template.scene.gz
  xcp_d/tests/test_utils_execsummary.py
  xcp_d/utils/execsummary.py
  xcp_d/workflows/anatomical/plotting.py
Labels: enhancement

#1371 Prepare for 0.10.5 release
  CITATION.cff
  docs/changes.md
Labels: maintenance, ignore-for-release
