Repository PennLINC/xcp_d, pull requests merged in 2025-02, with the labels that each got.

#1381 Only estimate head radius if necessary
  xcp_d/workflows/base.py
Labels: refactor

#1384 Simplify the brainsprite workflow setup
  xcp_d/workflows/anatomical/surface.py
Labels: refactor

#1388 Support `--abcc-qc` with `--file-format nifti`
  xcp_d/workflows/anatomical/parcellation.py
Labels: bug

#1382 Apply consistency across XCP-D quick-start instructions
  docs/usage.rst
Labels: documentation

#1392 Update mode documentation
  docs/conf.py
  docs/workflows.rst
  pyproject.toml
Labels: documentation

#1386 Add more OMP
  xcp_d/ingression/utils.py
  xcp_d/workflows/anatomical/plotting.py
  xcp_d/workflows/bold/connectivity.py
Labels: refactor

#1398 Do not attempt to concatenate runs when no runs in entity set are processed
  xcp_d/workflows/base.py
Labels: bug

#1397 Note that automatic head radius estimation gives higher values than 50
  xcp_d/cli/parser.py
Labels: documentation

#1379 Add session-id parameter
  xcp_d/cli/parser.py
  xcp_d/config.py
  xcp_d/reports/core.py
  xcp_d/tests/test_cli.py
Labels: enhancement

#1403 Add file lock to avoid concurrent edits
  xcp_d/interfaces/bids.py
  xcp_d/utils/bids.py
Labels: refactor

#1399 Make calculations robust to NaNs
  xcp_d/ingression/utils.py
  xcp_d/interfaces/connectivity.py
  xcp_d/interfaces/utils.py
  xcp_d/tests/test_despike.py
  xcp_d/tests/test_interfaces_utils.py
  xcp_d/tests/test_utils_confounds.py
  xcp_d/utils/confounds.py
  xcp_d/utils/plotting.py
  xcp_d/utils/restingstate.py
Labels: bug

#1401 Add colorbar to correlation matrix plot
  xcp_d/interfaces/connectivity.py
Labels: enhancement

#1394 Clarify mounting in apptainer instructions
  docs/usage.rst
Labels: documentation

#1409 Prepare for 0.10.6
  CITATION.cff
  docs/changes.md
Labels: maintenance, ignore-for-release
